config/routes.rb
Rails.application.routes.draw do
  root to: 'top#top'
  get'/home/about' => 'top#about'
	devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

	resources :users do
		resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get '/following' => 'users#following', as: 'following'
    get '/follower' => 'users#follower', as: 'follower'
	end
	resources :books do
		resources :book_comments, only: [:create, :destroy]
		resource :favorites, only: [:destroy, :create]
	end
  get '/search' => 'search#search', as: 'search'

  resources :chats, only: [:show]

  mount ActionCable.server => '/cable'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  	include JpPrefecture
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	    :recoverable, :rememberable, :validatable

	attachment :profile_image

	has_many :books, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :chats, dependent: :destroy
	has_many :user_rooms, dependent: :destroy

	has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
	has_many :followings, through: :active_relationships, source: :follower

	has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
	has_many :followers, through: :passive_relationships, source: :following

	validates :name, presence: true, length: { in: 2..20}
	validates :introduction, length: { maximum: 50 }
	validates :postal_code, presence: true, length: { minimum: 7 }
	validates :prefecture, presence: true
	validates :city, presence: true
	validates :street, presence: true

	jp_prefecture :prefecture, method_name: :pref

	def prefecture_name
	    JpPrefecture::Prefecture.find(code: prefecture).try(:name)
	end

	def prefecture_name=(prefecture_name)
	    self.prefecture_id = JpPrefecture::Prefecture.find(name: prefecture_name).code
	end

	def followed_by?(user)
		passive_relationships.find_by(following_id: user.id).present?
	end

	def user_address
		address = self.prefecture
		address += self.city
		return address
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    # super
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        ThanksMailer.send_confirm_to_user(resource).deliver_now
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit]

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
    @books = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      @users = User.all
      @book = Book.new
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
  	@user = current_user
  	@users = User.all
  	@book = Book.new
  end

  def following
    @user = User.find(params[:user_id])
    @following = @user.followings
  end

  def follower
    @user = User.find(params[:user_id])
    @follower = @user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :postal_code, :prefecture, :city, :street)
  end

  def correct_user
  	@user = User.find(params[:id])
  	if current_user.id != @user.id
  		redirect_to user_path(current_user)
  	end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_index.html.erb
<h2 style="margin: 20 0 10px 0;">Users</h2>
<table class="table">
	<th>Image</th>
	<th>Name</th>
	<th>Following</th>
	<th>Follower</th>
	<th></th>
	<th></th>
	<% users.each do |user| %>
	<tr>
		<td>
			<a><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.png" %></a>
		</td>
		<td>
			<%= link_to "#{user.name}", user_path(user.id) %>
		</td>
		<td>
			<%= link_to user.followings.count, user_following_path(user.id) %>
		</td>
		<td>
			<%= link_to user.followers.count, user_follower_path(user.id) %>
		</td>
		<td>
			<% if user != current_user %>
				<% if user.followed_by?(current_user) %>
					<p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %></p>
				<% else %>
					<p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-default follow" %></p>
				<% end %>
			<% end %>
		</td>
		<td>
			<%= link_to "Show", user_path(user.id) %>
		</td>
	</tr>
	<% end %>
</table>

app/views/users/_user_info.html.erb
<h2 style="margin: 20px 0 10px 0;">User info</h2>
<div class="img-box">
	<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.png" %>
</div>
<table class="table table-border">
	<tr>
		<th>Name</th>
		<td><%= user.name %></td>
	</tr>
	<tr>
		<th>Introduction</th>
		<td>
			<%= user.introduction %>
		</td>
	</tr>
	<tr>
		<th>Following</th>
		<td>
			<%= link_to user_following_path(user.id) do %>
				<%= user.followings.count %> people
			<% end %>
		</td>
	</tr>
	<tr>
		<th>Follower</th>
		<td>
			<%= link_to user_follower_path(user.id) do %>
				<%= user.followers.count %> people
			<% end %>
		</td>
	</tr>
	<tr>
		<% if current_user != user %>
			<% if user.followed_by?(current_user) %>
				<th></th>
				<td>
					<%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
				</td>
			<% else %>
				<th></th>
				<td>
					<%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-default follow"%>
				</td>
			<% end %>
			<tr>
				<th></th>
				<td><%= link_to "メッセージ", chat_path(user.id), class: "btn btn-default follow" %></td>
			</tr>
		<% end %>
	</tr>
</table>
<div class="">
	<%= link_to "",edit_user_path(user.id), {class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"}%>
</div>

app/views/users/edit.html.erb
<%= render 'layouts/header' %>
<div class="container">
    <h2 style="margin: 20px 0 10px 0;">Users info</h2>
        <% if @user.errors.any? %>
            <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        <% end %>
	<%= form_for(@user) do |f| %>
    <div class="edit-name" style="margin-bottom: 10px;">
        <label>Name</label>
        <%= f.text_field :name %>
    </div>
    <div class="edit-image" style="margin-bottom: 10px;">
        <label>Image</label>
        <%= f.attachment_field :profile_image %>
    </div>
    <div class="edit-intro" style="margin-bottom: 10px;">
    	<label>Introduction</label>
    	<%= f.text_area :introduction %>
    </div>
    <div class="actions" style="margin-bottom: 10px;">
        <input type="submit" name="commit" value="Update User" data-disable-with="Update User">
    <% end %>
    </div>
</div>
<%= render 'layouts/footer' %>

app/views/users/follower.html.erb
<%= render 'layouts/header' %>
<div class="container">
	<h1><strong><em><%= @user.name %></em></strong> @<%= @user.id %></h1>
	<h2><strong>フォロワー <%= @follower.count %>人</strong></h2>
	<% if @follower.present? %>
		<% @follower.each do |f| %>
			<table class="table" style="width: 500px;">
				<tr>
					<th>User ID</th>
					<th>User Name</th>
					<th></th>
				</tr>
				<tr>
					<td>@<%= f.id %></td>
					<td><%= link_to "#{f.name}", user_path(f.id) %></td>
					<% if current_user != f %>
						<% if f.followed_by?(current_user) %>
							<td>
								<%= link_to "フォロー中", user_relationships_path(f.id), method: :delete, class: "btn btn-primary" %>
							</td>
						<% else %>
							<td>
								<%=link_to "フォローする", user_relationships_path(f.id), method: :post, class: "btn btn-default follow" %>
							</td>
						<% end %>
					<% end %>
				</tr>
			</table>
		<% end %>
	<% end %>
</div>
<%= render 'layouts/footer' %>

app/views/users/following.html.erb
<%= render 'layouts/header' %>
<div class="container">
	<h1><strong><em><%= @user.name %></em></strong> @<%= @user.id %></h1>
	<h2><strong>フォロー中 <%= @following.count %>人</strong></h2>
	<% if @following.blank? %>
		<% if @user == current_user %>
			<h3><strong>フォローしている人はいません。</strong></h3>
			<%= link_to "フォローする人を探す", users_path %>
		<% end %>
	<% else %>
		<% @following.each do |f| %>
			<table class="table" style="width: 500px;">
				<tr>
					<th>User ID</th>
					<th>User Name</th>
					<th></th>
				</tr>
				<tr>
					<td>@<%= f.id %></td>
					<td><%= link_to "#{f.name}", user_path(f.id) %></td>
					<% if current_user != f %>
						<% if f.followed_by?(current_user) %>
							<td>
								<%= link_to "フォロー中", user_relationships_path(f.id), method: :delete, class: "btn btn-primary" %>
							</td>
						<% else %>
							<td>
								<%=link_to "フォローする", user_relationships_path(f.id), method: :post, class: "btn btn-default follow" %>
							</td>
						<% end %>
					<% end %>
				</tr>
			</table>
		<% end %>
	<% end %>
</div>
<%= render 'layouts/footer' %>

app/views/users/index.html.erb
<%= render 'layouts/header' %>
<div class="container">
	<div class="col-xs-3" style="padding: 0 15px;">
		<%= render 'user_info', user: current_user %>
		<%= render 'books/book_form', book: @book %>
	</div>
	<div class="col-xs-9">
		<%= render 'user_index', users: @users %>
	</div>
</div>
<%= render 'layouts/footer' %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>
<div class="container">
	<div class="col-xs-3" style="padding: 0 15px;">
		<%= render 'user_info', user: @user,now: ''%>
		<%= render 'books/book_form', book: @book %>
	</div>
	<%= render 'books/book_index', books: @books %>
	<% if current_user.id == @user.id %>
		<div class="col-xs-12">
			<h2>Gmap</h2>
			<div id='map' class="<%= @user.user_address %>"></div>
			<%= render 'layouts/footer' %>
			<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>
		</div>
	<% end %>
</div>