config/routes.rb
Rails.application.routes.draw do
  root to: 'top#top'
  get'/home/about' => 'top#about'
	devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

	resources :users do
		resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get '/following' => 'users#following', as: 'following'
    get '/follower' => 'users#follower', as: 'follower'
	end
	resources :books do
		resources :book_comments, only: [:create, :destroy]
		resource :favorites, only: [:destroy, :create]
	end
  get '/search' => 'search#search', as: 'search'

  resources :chats, only: [:show]

  mount ActionCable.server => '/cable'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :chats, dependent: :destroy
	has_many :user_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  	include JpPrefecture
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	    :recoverable, :rememberable, :validatable

	attachment :profile_image

	has_many :books, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :chats, dependent: :destroy
	has_many :user_rooms, dependent: :destroy

	has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
	has_many :followings, through: :active_relationships, source: :follower

	has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
	has_many :followers, through: :passive_relationships, source: :following

	validates :name, presence: true, length: { in: 2..20}
	validates :introduction, length: { maximum: 50 }
	validates :postal_code, presence: true, length: { minimum: 7 }
	validates :prefecture, presence: true
	validates :city, presence: true
	validates :street, presence: true

	jp_prefecture :prefecture, method_name: :pref

	def prefecture_name
	    JpPrefecture::Prefecture.find(code: prefecture).try(:name)
	end

	def prefecture_name=(prefecture_name)
	    self.prefecture_id = JpPrefecture::Prefecture.find(name: prefecture_name).code
	end

	def followed_by?(user)
		passive_relationships.find_by(following_id: user.id).present?
	end

	def user_address
		address = self.prefecture
		address += self.city
		return address
	end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

# room id 1
# user_room user_id current_user.id room_id 1
# user_room user_id current_user.id room_id 2
# user_room user_id 2 room_id 1

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :correct_book, only: [:edit]

	def show
		@book = Book.new
		@book_show = Book.find(params[:id])
		@user = @book_show.user
		@book_comment = BookComment.new
	end

	def edit
		@book = Book.new
		@book_edit = Book.find(params[:id])
	end

	def destroy
		@book_show = Book.find(params[:id])
		@book_show.destroy
		redirect_to books_path
	end

	def update
		@book_edit = Book.find(params[:id])
		if 	@book_edit.update(book_params)
			flash[:notice] = "You have updated book successfully."
			redirect_to book_path
		else
			render :edit
		end
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "You have created book successfully."
			redirect_to book_path(@book.id)
		else
			@books = Book.all
			@user = current_user
			render :index
		end
	end

	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end

	def correct_book
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect_to books_path
		end
	end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
	def show
	  	@currentUserRoom = UserRoom.where(user_id: current_user.id)
	  	if @currentUserRoom.blank?
	  		@room = Room.create
	  		UserRoom.create(user_id: params[:id], room_id: @room.id)
	  		UserRoom.create(user_id: current_user.id, room_id: @room.id)
	  	else
	  		@SearchRoom = @currentUserRoom.pluck(:room_id)
	  		@ExistRoom = UserRoom.find_by(room_id: @SearchRoom, user_id: params[:id])
	  		if @ExistRoom.nil?
	  			@room = Room.create
	  			UserRoom.create(user_id: params[:id], room_id: @room.id)
	  			UserRoom.create(user_id: current_user.id, room_id: @room.id)
	  		else
	  			@room = Room.find_by(id: @ExistRoom.room_id)
	  		end
	  	end
	  	@user = User.find(params[:id])
	  	@chatall = Chat.where(room_id: @room.id)
  	end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	before_action :authenticate_user!, except: [:top, :about]
	def top
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit]

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
    @books = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      @users = User.all
      @book = Book.new
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
  	@user = current_user
  	@users = User.all
  	@book = Book.new
  end

  def following
    @user = User.find(params[:user_id])
    @following = @user.followings
  end

  def follower
    @user = User.find(params[:user_id])
    @follower = @user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :postal_code, :prefecture, :city, :street)
  end

  def correct_user
  	@user = User.find(params[:id])
  	if current_user.id != @user.id
  		redirect_to user_path(current_user)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="row footer">
  <div class="col-xs-3 col-xs-offset-9">
    <p>CopyRight Infratop.inc</p>
 </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar nabvar-fixed-top navbar-inverse">
	<div class="container">
		<span class="col-xs-7" style="font-size: 20px; color: #fff ;">Bookers</span>
		<ul class="col-xs-5">
			<% if user_signed_in? %>
				<li style="display: inline-block; padding: 15px;">
					<%= link_to " Home",user_path(current_user),{class: "text-muted glyphicon glyphicon-home" } %>
				</li>
				<li style="display: inline-block; padding: 15px;">
					<%= link_to " Users",users_path,{class: "text-muted glyphicon glyphicon-user"} %>
	   			</li>
	   			<li style="display: inline-block; padding: 15px;">
	   				<%= link_to " Books",books_path,{class: "text-muted glyphicon glyphicon-book"} %>
	   			</li>
				<li style="display: inline-block; padding: 15px;" style="display: inline-block; padding: 15px;">
	        		<%= link_to " logout", destroy_user_session_path, method: :delete ,:class => "text-muted glyphicon glyphicon-log-out" %>
	   			</li>
			<% else %>
				<li>
					<a href="/">Home</a>
				</li>
				<li>
					<a href="/home/about">About</a>
				</li>
				<li class="">
			        <%= link_to "sign up", new_user_registration_path %>
			    </li>
			    <li class="">
			        <%= link_to "login", new_user_session_path %>
			    </li>
			<%  end %>
		</ul>
	</div>
</header>
<%= render 'layouts/search' %>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
	<div style="text-align: center;">
		<%= form_tag(search_path,:method => 'get') do %>
		  <%= text_field_tag :input %>
		  <%= select_tag :model, options_for_select({"User名で検索する" => "user", "Bookのタイトルで検索する" => "book" }) %>
		  <%= select_tag :sort, options_for_select({"完全一致" => "all", "前方一致" => "front", "後方一致" => "back", "部分一致" => "part"}) %>
		  <%= submit_tag '検索' %>
		<% end %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>